# This name will appear in the Actions tab
name: Manual Claude Code Review

on:
  # This enables the workflow to be triggered manually from the Actions tab
  workflow_dispatch:
    # These are the inputs the user will provide when running the workflow
    inputs:
      pull_request_number:
        description: 'The number of the pull request you want Claude to review'
        required: true
        type: string

jobs:
  claude-manual-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Write permission is needed for Claude to post the review comment on the PR
      pull-requests: write
      issues: read
      id-token: write
    
    steps:
      # This step checks out the specific code from the pull request branch
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.inputs.pull_request_number }}/head

      # This step runs the Claude action
      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This tells the action which PR to review and comment on, using the number you provided
          pull_request_number: ${{ github.event.inputs.pull_request_number }}
          
          # This is the prompt that instructs Claude on how to perform the review.
          # It runs without needing an @claude mention in the PR itself.
          direct_prompt: |
            Please perform a thorough review of this pull request. Provide feedback on:
            - Code quality and adherence to best practices
            - Potential bugs, logic errors, or edge cases
            - Performance considerations and potential optimizations
            - Security vulnerabilities or concerns
            - Clarity and readability of the code
            - Adequacy of test coverage
            
            Please be constructive, clear, and helpful in your feedback.

          # Optional: Specify a more powerful model if needed (costs may be higher)
          # model: "claude-opus-4-20250514"
          
          # Optional: Use a "sticky comment" to have Claude update its previous review
          # instead of posting a new one every time you re-run the action on the same PR.
          # use_sticky_comment: true
